# Problem 1: If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. 
# The sum of these multiples is 23.
# Find the sum of all the multiples of 3 or 5 below 1000.

sum = 0
for x in range(1,1000): # natural numbers so starting at 1
    if x % 3 == 0 or x % 5 == 0:
        sum += x
    
print(sum) # gives the answer 233168

# Problem 2: Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find 
# the sum of the even-valued terms.

def fibFinder(before, current, target):
    newSum = before + current
    if newSum >= target:
        return 0
    elif newSum % 2 == 0:
        return newSum  + fibFinder(current, newSum, target)
    else:
        return 0 + fibFinder(current, newSum, target)

print(fibFinder(1,1,4000000)) # to start from 1 and 2 the before had to have been one. Answer is 4613732.